apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: rabbitmqmonitoring/producer
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  labels:
    app: producer
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - port: 8080
      name: http
